{
 "title": "Live daten",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Live Wetter Itzehoe",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cities_current",
     "rawSql": "SELECT temperature, rain, humidity FROM cities_current.livedata WHERE city = 'Itzehoe' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Live Wetter Brocken",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cities_current",
     "rawSql": "SELECT temperature, rain, humidity FROM cities_current.livedata WHERE city = 'Brocken' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Live Wetter Troll",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cities_current",
     "rawSql": "SELECT temperature, rain, humidity FROM cities_current.livedata WHERE city = 'Troll' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Live Wetter München",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cities_current",
     "rawSql": "SELECT temperature, rain, humidity FROM cities_current.livedata WHERE city = 'Muenchen' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Live Wetter Goiania",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cities_current",
     "rawSql": "SELECT temperature, rain, humidity FROM cities_current.livedata WHERE city = 'Goiania' LIMIT 50 "
    }
   ]
  },
  {
   "title": "Live Wetter Jeju",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "cities_current",
     "rawSql": "SELECT temperature, rain, humidity FROM cities_current.livedata WHERE city = 'Jeju' LIMIT 50 "
    }
   ]
  }
 ]
}