version: '3'
services:

  db:
    image: mysql
    ports: ['3307:3307']
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55


  dwd-exporter:
    build: "./"
    ports:
            - "9110:9110"
    restart: unless-stopped
    networks:
            - monitoring

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring


  grafana:
     image: grafana/grafana
     ports:
       - 3000:3000
     environment:
       - GF_SECURITY_ADMIN_USER=MyLittleEdi3978     
       - GF_SECURITY_ADMIN_PASSWORD=HappyHippo
     networks:
       - monitoring

networks:
  monitoring:
    driver: bridge
    #external: true - bringt nur was wenn man schon ein passendes netzwerk hat. auskommentiert erstellt er ein neues netztwerk

